CREATE VIEW student_info AS
    SELECT std_id, exam_result, gpa, department, consultant_id, fname, lname
    FROM students;

GRANT SELECT ON student_info TO it_staff;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO it_staff;
REVOKE SELECT ON students, login_infos FROM it_staff;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO manager;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO student;

GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO manager;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO student;

GRANT ALL PRIVILEGES ON ALL PROCEDURES IN SCHEMA public TO manager;
GRANT ALL PRIVILEGES ON ALL PROCEDURES IN SCHEMA public TO student;

GRANT ALL PRIVILEGES ON ALL ROUTINES IN SCHEMA public TO manager;
GRANT ALL PRIVILEGES ON ALL ROUTINES IN SCHEMA public TO student;

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO manager;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO student;

